
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Oct 20 02:45:09 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 47;
  public static final int LBRACKET = 32;
  public static final int CONST = 22;
  public static final int GE = 42;
  public static final int CONTINUE = 36;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int INTERFACE = 49;
  public static final int DECR = 30;
  public static final int INCR = 29;
  public static final int MINUS = 14;
  public static final int RPAREN = 7;
  public static final int AND = 44;
  public static final int LT = 39;
  public static final int OR = 43;
  public static final int COMMA = 11;
  public static final int CLASS = 48;
  public static final int DIV = 16;
  public static final int PLUS = 10;
  public static final int IF = 27;
  public static final int DOT = 18;
  public static final int LE = 40;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 33;
  public static final int EQUAL = 8;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int NUMBER = 23;
  public static final int MOD = 17;
  public static final int NEQ = 38;
  public static final int BREAK = 35;
  public static final int IDENT = 24;
  public static final int VOID = 13;
  public static final int EQ = 37;
  public static final int TIMES = 15;
  public static final int UNION = 21;
  public static final int LBRACE = 3;
  public static final int ELSE = 28;
  public static final int READ = 31;
  public static final int WHILE = 46;
  public static final int CHARCONST = 25;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 26;
  public static final int EXTENDS = 19;
  public static final int PROG = 2;
  public static final int GT = 41;
  public static final int DO = 45;
  public static final int PRINT = 12;
  public static final int SET = 20;
}

